// AUTO-GENERATED by scripts/build-chapters.mjs — do not edit by hand.
// Static require() map so Metro can bundle audio clips referenced by id
// from {{audio:NAME}} markers in chapter markdown.

export const AUDIO_CLIPS: Record<string, number> = {
  'kookaburra': require('@/assets/audio/Kookaburra.wav'),
};
