// AUTO-GENERATED by scripts/build-chapters.mjs — do not edit by hand.
// Static require() map so chapter markdown can reference images by
// filename (e.g. `![Caption](butterfly.png)`).

export const CONTENT_IMAGES: Record<string, number> = {
  'butterfly.png': require('@/assets/images/butterfly.png'),
  'caterpillar.png': require('@/assets/images/caterpillar.png'),
  'cocoon.png': require('@/assets/images/cocoon.png'),
  'cover_image.png': require('@/assets/images/cover_image.png'),
  'ethan-signature.png': require('@/assets/images/ethan-signature.png'),
};
