// AUTO-GENERATED by scripts/build-chapters.mjs — do not edit by hand.
// Static-import map of every .svg in assets/logos/ so MoreFromEthan can
// resolve a brand logo by filename.

import type { ComponentType } from 'react';
import type { SvgProps } from 'react-native-svg';
import Logo0 from '@/assets/logos/Instagram_Glyph_Gradient.svg';
import Logo1 from '@/assets/logos/instagram.svg';
import Logo2 from '@/assets/logos/telegram.svg';
import Logo3 from '@/assets/logos/youtube.svg';
import Logo4 from '@/assets/logos/ywe.svg';

export const SVG_LOGOS: Record<string, ComponentType<SvgProps>> = {
  'Instagram_Glyph_Gradient.svg': Logo0,
  'instagram.svg': Logo1,
  'telegram.svg': Logo2,
  'youtube.svg': Logo3,
  'ywe.svg': Logo4,
};
